version: '3.7'

services:
  afido:
    image: voko-afido
    build: https://github.com/revuloj/voko-afido.git
      # restart: always
#    environment:
#      - GIT_REPO_REVO=https://github.com/revuloj/revo-fonto-testo.git
    networks:
      - reto
    #volumes:
      #- afido-dict:/home/afido/dict
#      - mail:/var/mail
    environment:
      #GIT_REPO_REVO: revo-fonto-testo
      GIT_REPO_REVO: test-repo
    secrets:
#      - voko-formiko.ssh_key
      - voko.redaktantoj.json
        # SSH deploy key por puŝi ŝangojn al git-arĥivo
      #- voko-afido.github_key
        # "Github personal access token" por uzi Github REST-Api, t.e. legi kaj skribi ĉe gists.github.com
      - voko-afido.access_token
        # Sigelilo estas uzata por sigeli redaktojn uzante HMAC
      - voko-afido.sigelilo
        # Agordo de poŝtservilo por sendi raportojn al redaktantoj
      - voko-afido.smtp_server
      - voko-afido.smtp_user
      - voko-afido.smtp_password

    # necesas unufoje akcepti la ssh-servo-ŝlosilon de afido
    # KOREKTU: ofte afido ankoraŭ ne estas aktiva, iel ni devos atendi ĝis afido reagas kaj funkcias la komando!
#    command: >
#      bash -c 
#      "su -c 'ssh -i /run/secrets/voko-formiko.ssh_key -o StrictHostKeyChecking=no -o PasswordAuthentication=no afido@afido exit' formiko
#      && cron -f"

#  afido:
#    image: voko-afido
#    build: https://github.com/revuloj/voko-afido.git
#    # command: processmail.pl
#    networks:
#      - ghardeno
#    volumes:
#      - type: bind
#        source: ./cvsroot
#        target: /home/afido/dict/cvsroot
#      - type: bind
#        source: ./revo/xml
#        target: /home/afido/dict/xml        
#      - type: bind
#        source: ./revo-fonto
#        target: /home/afido/dict/revo-fonto        
##      - xml:/home/afido/dict/xml # la artikoloj
##      - cvsroot:/home/afido/dict/cvsroot # $CVSROOT
#      - afido:/var/afido # tmp, log
#      - mail:/var/mail
#    environment:
#      - CVSROOT=/home/afido/dict/cvsroot
#    secrets:
#      - voko.redaktantoj
#      - voko-afido.ssh_key.pub
#      - voko-afido.github_key
#      - voko-afido.smtp_server
#      - voko-afido.smtp_user
#      - voko-afido.smtp_password
#      #- voko-tomocero.saslpassword
#
#  tomocero:
#    image: voko-tomocero
#    build: https://github.com/revuloj/voko-tomocero.git
#    command: /usr/lib/postfix/master -d
#    volumes:
#      # eble ni eksterigu ankaŭ /var/spool/postfix resp. tutan /var/spool
#      - mail:/var/mail
#      - spool:/var/spool
#    secrets:
#      - voko-tomocero.pop3_server
#      - voko-tomocero.pop3_user
#      - voko-tomocero.pop3_password
#      - voko-tomocero.myhostname
#      - voko-tomocero.saslpassword
#      - voko-tomocero.relayhost
#      - voko-tomocero.relayaddress
#      - voko-tomocero.relaypassword
#    #expose: 25, 465

secrets:
#  voko-tomocero.pop3_server:
#    external: true
#  voko-tomocero.pop3_user:
#    external: true
#  voko-tomocero.pop3_password:
#    external: true
#  voko-tomocero.myhostname:
#    external: true
#  voko-tomocero.saslpassword:
#    external: true
#  voko-tomocero.relayhost:
#    external: true
#  voko-tomocero.relayaddress:
#    external: true
#  voko-tomocero.relaypassword:
#    external: true
#
#  voko-formiko.ssh_key:
#    external: true
#
#  voko-afido.ssh_key.pub:
#    external: true
  voko-afido.access_token:
    external: true
  #voko-afido.github_key:
  #  external: true
  voko-afido.sigelilo:
    external: true

  voko-afido.smtp_server:
    external: true
  voko-afido.smtp_user:
    external: true
  # uzante tomoceron por sendo, sama kiel sasl-password
  voko-afido.smtp_password:
    external: true

  voko.redaktantoj.json:
    #external: true
    file: ${HOME}/etc/redaktantoj.json

#volumes:
#  mail:
#  spool:
#  afido:

#  xml:
#  cvsroot:
#    external: true
  
networks:
  reto:
#    external: true

