version: '3.7'

services:
  afido:
    image: voko-afido
    build: https://github.com/revuloj/voko-afido.git
      # restart: always
#    environment:
#      - GIT_REPO_REVO=https://github.com/revuloj/revo-fonto-testo.git
    networks:
      - reto
    #volumes:
      #- afido-dict:/home/afido/dict
#      - mail:/var/mail
    environment:
      #GIT_REPO_REVO: revo-fonto-testo
      GIT_REPO_REVO: test-repo
      REVO_HOST: araneo
      CGI_USER: steloj
    secrets:
#      - voko-formiko.ssh_key
      - voko.redaktantoj.json
        # SSH deploy key por puŝi ŝangojn al git-arĥivo
      #- voko-afido.github_key
        # "Github personal access token" por uzi Github REST-Api, t.e. legi kaj skribi ĉe gists.github.com
      - voko-afido.access_token
        # Sigelilo estas uzata por sigeli redaktojn uzante HMAC
      - voko-afido.sigelilo
        # Agordo de poŝtservilo por sendi raportojn al redaktantoj
      - voko-afido.smtp_server
      - voko-afido.smtp_user
      - voko-afido.smtp_password
      - voko-araneo.cgi_password


    # necesas unufoje akcepti la ssh-servo-ŝlosilon de afido
    # KOREKTU: ofte afido ankoraŭ ne estas aktiva, iel ni devos atendi ĝis afido reagas kaj funkcias la komando!
#    command: >
#      bash -c 
#      "su -c 'ssh -i /run/secrets/voko-formiko.ssh_key -o StrictHostKeyChecking=no -o PasswordAuthentication=no afido@afido exit' formiko
#      && cron -f"

  abelo:
    image: voko-abelo
    build: https://github.com/revuloj/voko-abelo.git
    # command: --default-authentication-plugin=mysql_native_password
    # restart: always
    #expose:
    #  - 3306
    networks:
      - reto
    secrets:
      - voko-abelo.mysql_root_password
      - voko-abelo.mysql_password
      #- voko.redaktantoj
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/voko-abelo.mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/voko-abelo.mysql_password
      MYSQL_DATABASE: db314802x3159000
      MYSQL_USER: s314802_3159000

  araneo:
    image: voko-araneo
    build: https://github.com/revuloj/voko-araneo.git
    # restart: always
    ports:
      - 8088:80
    networks:
      - reto
    depends_on:
      - abelo
    volumes:
      - alveno:/hp/af/ag/ri//www/alveno
    secrets:
      - voko-abelo.mysql_password
      # uzata por eksporto de lastaj ŝanĝoj:
      - voko-abelo.mysql_root_password
      - voko-araneo.cgi_password
    #environment:
    #  EMAIL_SENDER_TRANSPORT: SMTPS
    #  EMAIL_SENDER_TRANSPORT_ssl: ssl
      # momente la sekvontoj valoroj estas en sekretoj:
      # voko-afido.smtp_server 
      # voko-afido.smtp_user 
      # voko-afido.smtp_password resp. voko-tomocero.saslpassword
      # ni prefere uzu pli ĝeneralajn sekretoj voko.smtp_server ktp.
      # kaj kreu la mediovariablojn ekz. en entry-point.sh...
      #EMAIL_SENDER_TRANSPORT_host: tomocero
      #EMAIL_SENDER_TRANSPORT_sasl_username: tomocero@tomocero
      #EMAIL_SENDER_TRANSPORT_sasl_password: sekreta

#
#  tomocero:
#    image: voko-tomocero
#    build: https://github.com/revuloj/voko-tomocero.git
#    command: /usr/lib/postfix/master -d
#    volumes:
#      # eble ni eksterigu ankaŭ /var/spool/postfix resp. tutan /var/spool
#      - mail:/var/mail
#      - spool:/var/spool
#    secrets:
#      - voko-tomocero.pop3_server
#      - voko-tomocero.pop3_user
#      - voko-tomocero.pop3_password
#      - voko-tomocero.myhostname
#      - voko-tomocero.saslpassword
#      - voko-tomocero.relayhost
#      - voko-tomocero.relayaddress
#      - voko-tomocero.relaypassword
#    #expose: 25, 465

secrets:
#  voko-tomocero.pop3_server:
#    external: true
#  voko-tomocero.pop3_user:
#    external: true
#  voko-tomocero.pop3_password:
#    external: true
#  voko-tomocero.myhostname:
#    external: true
#  voko-tomocero.saslpassword:
#    external: true
#  voko-tomocero.relayhost:
#    external: true
#  voko-tomocero.relayaddress:
#    external: true
#  voko-tomocero.relaypassword:
#    external: true

  voko-abelo.mysql_root_password:
    external: true
  voko-abelo.mysql_password:
    external: true

  voko-araneo.cgi_password:
    external: true
#  voko-araneo.cgi_user:
#    external: true        
#
#  voko-formiko.ssh_key:
#    external: true
#
#  voko-afido.ssh_key.pub:
#    external: true
  voko-afido.access_token:
    external: true
  #voko-afido.github_key:
  #  external: true
  voko-afido.sigelilo:
    external: true

  voko-afido.smtp_server:
    external: true
  voko-afido.smtp_user:
    external: true
  # uzante tomoceron por sendo, sama kiel sasl-password
  voko-afido.smtp_password:
    external: true

  voko.redaktantoj.json:
    #external: true
    file: ${HOME}/etc/redaktantoj.json

volumes:
  alveno:

#  mail:
#  spool:
#  afido:

#  xml:
#  cvsroot:
#    external: true
  
networks:
  reto:
#    external: true

