version: '3.1'

services:
  formiko:
    image: voko-formiko
    build: 
      context: .
      dockerfile: Dockerfile
    # restart: always

  afido:
    image: voko-afido
    build: https://github.com/revuloj/voko-afido.git
    # command: processmail.pl
    volumes:
      - xml:/home/afido/dict/xml # la artikoloj, devas esti kreita per "cvs co"
      - var_afido:/var/afido # tmp, log
    secrets:
      - voko.redaktantoj
      - voko-afido.pop3_server
      - voko-afido.pop3_user
      - voko-afido.pop3_password
      - voko-afido.smtp_server
      - voko-afido.smtp_user
      - voko-afido.smtp_password

  vaneso-cvs:
    image: voko-vaneso
    build: https://github.com/revuloj/voko-vaneso.git
    command: mirror.pl cvs
    volumes:
      - mirrordat:/home/vaneso/mirrordat
      - log:/home/vaneso/log

  vaneso-revo:
    image: voko-vaneso
    build: https://github.com/revuloj/voko-vaneso.git
    command: mirror.pl revo
    volumes:
      - mirrordat:/home/vaneso/mirrordat
      - log:/home/vaneso/log

# kreu sekretojn ekzemple tiel, kondiĉe ke vi uzas propran poŝtfakon
# redaktoservo@provizanto.org por ricevi kaj forsendi artikolojn
#   echo "mail.provizanto.org" | docker secret create voko-afido.pop3_server -
#   echo "redaktoservo@provizanto.org" | docker secret create voko-afido.pop3_user -
#   echo "MiaTr3SekretaP4svorto" | docker secret create voko-afido.pop3_password -
#   
#   echo "smtp.provizanto.org" | docker secret create voko-afido.smtp_server -
#   echo "redaktoservo@provizanto.org" | docker secret create voko-afido.smtp_user -
#   echo "MiaTr3SekretaP4svorto" | docker secret create voko-afido.smtp_password -
# Uzante la procesumon voko-tomocero por forsendo de retpoŝtoj vi anstataŭe donu por smtp
# la sekvan agordon. La avantaĝo estas, ke tomocero transsendas la retpoŝtojn en serioj
# kaj tiel ne por ĉiu unuopa retpoŝto okazas rekonekto, kion kelkaj provizantoj
# malhelpas per kelkminuta deviga paŭzo.
#   echo "voko-tomocero" | docker secret create voko-afido.smtp_server -
#   echo "" | docker secret create voko-afido.smtp_user -
#   echo "" | docker secret create voko-afido.smtp_password -

secrets:
  voko-afido.pop3_server:
    external: true
  voko-afido.pop3_user:
    external: true
  voko-afido.pop3_password:
    external: true
  voko-afido.smtp_server:
    external: true
  voko-afido.smtp_user:
    external: true
  voko-afido.smtp_password:
    external: true
  voko.redaktantoj:
    #external: true
    file: ${HOME}/etc/redaktantoj

volumes:
  xml:
  mirrordat:
  log:
  var_afido:
  


