version: '3.7'

services:
  formiko:
    image: voko-formiko
    build: https://github.com/revuloj/voko-formiko.git
      # restart: always
    volumes:
      - formiko-revo:/home/formiko/revo 
      - formiko-tmp:/home/formiko/tmp
      - formiko-log:/home/formiko/log
    secrets:
      - voko-formiko.ssh_key
    configs:
      - source: voko-formiko.agordo-cron
        #uid: '1001'
        mode: 0644
      - source: voko-formiko.agordo-redaktoservo
        target: /home/formiko/etc/redaktoservo-agordo
        mode: 0444
    #healthcheck:
    #  test: ["CMD", "health_check_cron.sh"]
    #  interval: 5m
    #  timeout: 3s

  afido:
    image: voko-afido
    build: https://github.com/revuloj/voko-afido.git
    # command: processmail.pl
    volumes:
      - xml:/home/afido/dict/xml # la artikoloj, devas esti kreita per "cvs co"
      - afido:/var/afido # tmp, log
      - mail:/var/mail
    secrets:
      - voko.redaktantoj
      - voko-afido.ssh_key.pub
      - voko-afido.smtp_server
      - voko-afido.smtp_user
      - voko-afido.smtp_password
      #- voko-tomocero.saslpassword

  tomocero:
    image: voko-tomocero
    build: https://github.com/revuloj/voko-tomocero.git
    command: /usr/lib/postfix/master -d
    volumes:
      # eble ni eksterigu ankaŭ /var/spool/postfix resp. tutan /var/spool
      - mail:/var/mail
      - spool:/var/spool
    secrets:
      - voko-tomocero.pop3_server
      - voko-tomocero.pop3_user
      - voko-tomocero.pop3_password
      - voko-tomocero.myhostname
      - voko-tomocero.saslpassword
      - voko-tomocero.relayhost
      - voko-tomocero.relayaddress
      - voko-tomocero.relaypassword
    #expose: 25, 465
##
##  vaneso-cvs:
##    image: voko-vaneso
##    build: https://github.com/revuloj/voko-vaneso.git
##    command: mirror.pl cvs
##    volumes:
##      - mirrordat:/home/vaneso/mirrordat
##      - vaneso-log:/home/vaneso/log
##
##  vaneso-revo:
##    image: voko-vaneso
##    build: https://github.com/revuloj/voko-vaneso.git
##    command: mirror.pl revo
##    volumes:
##      - mirrordat:/home/vaneso/mirrordat
##      - vaneso-log:/home/vaneso/log
##

# kreu sekretojn ekzemple tiel, kondiĉe ke vi uzas propran poŝtfakon
# redaktoservo@provizanto.org por ricevi kaj forsendi artikolojn
#   echo "mail.provizanto.org" | docker secret create voko-afido.pop3_server -
#   echo "redaktoservo@provizanto.org" | docker secret create voko-afido.pop3_user -
#   echo "MiaTr3SekretaP4svorto" | docker secret create voko-afido.pop3_password -
#   
#   echo "smtp.provizanto.org" | docker secret create voko-afido.smtp_server -
#   echo "redaktoservo@provizanto.org" | docker secret create voko-afido.smtp_user -
#   echo "MiaTr3SekretaP4svorto" | docker secret create voko-afido.smtp_password -
# Uzante la procesumon voko-tomocero por forsendo de retpoŝtoj vi anstataŭe donu por smtp
# la sekvan agordon. La avantaĝo estas, ke tomocero transsendas la retpoŝtojn en serioj
# kaj tiel ne por ĉiu unuopa retpoŝto okazas rekonekto, kion kelkaj provizantoj
# malhelpas per kelkminuta deviga paŭzo.
#   echo "voko-tomocero" | docker secret create voko-afido.smtp_server -
#   echo "" | docker secret create voko-afido.smtp_user -
#   echo "" | docker secret create voko-afido.smtp_password -

secrets:
  voko-tomocero.pop3_server:
    external: true
  voko-tomocero.pop3_user:
    external: true
  voko-tomocero.pop3_password:
    external: true
  voko-tomocero.myhostname:
    external: true
  voko-tomocero.saslpassword:
    external: true
  voko-tomocero.relayhost:
    external: true
  voko-tomocero.relayaddress:
    external: true
  voko-tomocero.relaypassword:
    external: true

  voko-formiko.ssh_key:
    external: true

  voko-afido.ssh_key.pub:
    external: true
  voko-afido.smtp_server:
    external: true
  voko-afido.smtp_user:
    external: true
  # uzante tomoceron por sendo, sama kiel sasl-password
  voko-afido.smtp_password:
    external: true

  voko.redaktantoj:
    #external: true
    file: ${HOME}/etc/redaktantoj
    
configs:
  # alternatice uzu file: ...
  # por rekte lasi la agordon sur la docker-gastiganto
  voko-formiko.agordo-cron:
    external: true
  voko-formiko.agordo-redaktoservo:
    external: true

volumes:
  mail:
  spool:
  xml:
  mirrordat:
  vaneso-log:
  afido:
  formiko-revo:
  formiko-tmp:
  formiko-log:
  


