apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    cmp: abelo
  name: abelo
spec:
  replicas: 1
  selector:
    matchLabels:
      cmp: abelo  
  strategy: {}
  template:
    metadata:
      labels:
        cmp: abelo
    spec:
      containers:
      - name: abelo
        image: voko-abelo
        env:
        - name: MYSQL_DATABASE
          value: usr_web277_1
        - name: MYSQL_PASSWORD_FILE
          value: /secrets/voko-abelo.mysql_password
        - name: MYSQL_ROOT_PASSWORD_FILE
          value: /secrets/voko-abelo.mysql_root_password
        - name: MYSQL_USER
          value: web277
        volumeMounts:
        - mountPath: /secrets/
          name: secrets-vol
          readOnly: true
        resources: {}
      restartPolicy: Always
      volumes:        
      - name: secrets-vol
        projected:
          sources:      
          - secret:
              name: voko-abelo
#              items:
#              - key: voko-abelo.mysql_root_password    
#                path: voko-abelo.mysql_root_password      
#              - key: voko-abelo.mysql_password    
#                path: voko-abelo.mysql_password      
status: {}
