apiVersion: v1
kind: Service
metadata:
  labels:
    service: abelisto
  name: abelisto
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8080
  selector:
    cmp: abelisto
status:
  loadBalancer: {}
