apiVersion: v1
kind: Service
metadata:
  labels:
    service: araneo
  name: araneo
spec:
  ports:
  - name: "http"
    port: 8088
    targetPort: 80
  selector:
    app: araneo
status:
  loadBalancer: {}
