apiVersion: v1
kind: Service
metadata:
  labels:
    service: cikado
  name: cikado
spec:
  ports:
  - name: "8082"
    port: 8082
    targetPort: 8082
  selector:
    cmp: cikado
status:
  loadBalancer: {}
